'use client';

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '../../../store/authStore';
import api from '../../../lib/axios';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import InteractiveMCQ from '../../../components/InteractiveMCQ';

interface MCQ {
  question: string;
  options: string[];
  answer: string;
  explanation: string;
}

interface QA {
  question: string;
  answer: string;
}

interface ChatMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
}

interface ChatHistory {
  _id: string;
  title: string;
  messages: ChatMessage[];
  createdAt: string;
  isShared?: boolean;
}

export default function HistoryPage() {
  const router = useRouter();
  const { user } = useAuthStore();
  const [history, setHistory] = useState<ChatHistory[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  
  const [selectedChat, setSelectedChat] = useState<ChatHistory | null>(null);
  const [chatType, setChatType] = useState<'mcq' | 'notes' | 'qa' | 'chat' | null>(null);
  const [parsedData, setParsedData] = useState<any>(null);
  const [isSharing, setIsSharing] = useState(false);
  const [shareCopied, setShareCopied] = useState(false);

  useEffect(() => {
    if (!user) {
      router.push('/register');
      return;
    }
    
    fetchHistory();
  }, [user, router]);

  const fetchHistory = async () => {
    try {
      setLoading(true);
      const response = await api.get('/data/chatshistory');
      setHistory(response.data.data || []);
    } catch (err: any) {
      setError(err.response?.data?.error || 'Failed to fetch history');
    } finally {
      setLoading(false);
    }
  };

  const handleSelectChat = (chat: ChatHistory) => {
    setSelectedChat(chat);
    
    let type: 'mcq' | 'notes' | 'qa' | 'chat' = 'mcq';
    if (chat.title.startsWith('Notes on')) type = 'notes';
    else if (chat.title.startsWith('Q&A on')) type = 'qa';
    else if (chat.title.startsWith('Chat:')) type = 'chat';
    
    setChatType(type);

    const assistantMsg = chat.messages.find(m => m.role === 'assistant');
    if (assistantMsg) {
      if (type === 'notes' || type === 'chat') {
        setParsedData(assistantMsg.content);
      } else {
        try {
          const parsed = JSON.parse(assistantMsg.content);
          setParsedData(Array.isArray(parsed) ? parsed : []);
        } catch (e) {
          console.error("Failed to parse history data:", e);
          setParsedData(null);
        }
      }
    } else {
      setParsedData(null);
    }
  };

  const handleDownloadPdf = async () => {
    if (typeof window === 'undefined' || !selectedChat) return;
    
    // Dynamically import to avoid SSR issues
    const html2pdf = (await import('html2pdf.js')).default;
    
    const element = document.getElementById('pdf-content');
    if (!element) return;
    
    // Add the site link temporarily at the bottom
    const linkDiv = document.createElement('div');
    linkDiv.className = 'mt-10 pt-6 border-t border-border-subtle text-center text-sm text-text-secondary';
    linkDiv.innerHTML = `Generated by <strong>Prepiqo</strong> - <a href="${window.location.origin}" style="color: #4f46e5; text-decoration: none;">${window.location.origin}</a>`;
    element.appendChild(linkDiv);
    
    const opt = {
      margin:       15,
      filename:     `${selectedChat.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`,
      image:        { type: 'jpeg' as const, quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true },
      jsPDF:        { unit: 'mm' as const, format: 'a4', orientation: 'portrait' as const },
      pagebreak:    { mode: ['css', 'legacy'], avoid: ['.pdf-avoid-break', 'p', 'li', 'h1', 'h2', 'h3', 'h4', 'div.bg-white'] }
    };
    
    // Save PDF
    await html2pdf().from(element).set(opt).save();
    
    // Remove the temporary link div
    element.removeChild(linkDiv);
  };

  const handleToggleShare = async () => {
    if (!selectedChat) return;
    
    try {
      setIsSharing(true);
      const response = await api.post(`/data/chatshistory/${selectedChat._id}/share`);
      
      if (response.data.success) {
        // Update local state
        const updatedChat = { ...selectedChat, isShared: response.data.isShared };
        setSelectedChat(updatedChat);
        setHistory(history.map(chat => chat._id === updatedChat._id ? updatedChat : chat));
      }
    } catch (err: any) {
      setError('Failed to toggle sharing');
    } finally {
      setIsSharing(false);
    }
  };

  const copyShareLink = () => {
    if (!selectedChat) return;
    const link = `${window.location.origin}/share/${selectedChat._id}`;
    navigator.clipboard.writeText(link);
    setShareCopied(true);
    setTimeout(() => setShareCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center p-8">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-brand"></div>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-6xl mx-auto h-full flex flex-col">
      <h1 className="text-3xl font-bold mb-8">Chat History</h1>
      
      {error && (
        <div className="p-4 mb-6 bg-red-50 text-red-600 rounded-lg border border-red-100">
          {error}
        </div>
      )}

      {history.length === 0 ? (
        <div className="text-center py-20 bg-white rounded-xl border border-border-subtle">
          <svg className="w-16 h-16 mx-auto text-border-strong mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 002-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path></svg>
          <h2 className="text-xl font-semibold mb-2">No History Yet</h2>
          <p className="text-text-secondary mb-6">You haven't generated any content yet.</p>
          <button 
            onClick={() => router.push('/dashboard')}
            className="px-6 py-2 bg-brand text-white rounded-lg font-medium hover:bg-brand/90 transition-colors"
          >
            Generate Now
          </button>
        </div>
      ) : (
        <div className="flex flex-col md:flex-row gap-8 flex-1 min-h-0">
          {/* History List */}
          <div className="w-full md:w-1/3 bg-white rounded-xl border border-border-subtle flex flex-col overflow-hidden h-[600px]">
            <div className="p-4 border-b border-border-subtle bg-bg-secondary font-semibold">
              Recent Generations
            </div>
            <div className="overflow-y-scroll flex-1 p-2 pr-3 space-y-2 custom-scrollbar">
              {history.map((chat) => (
                <button
                  key={chat._id}
                  onClick={() => handleSelectChat(chat)}
                  className={`w-full text-left p-4 rounded-lg transition-colors ${selectedChat?._id === chat._id ? 'bg-brand text-white' : 'hover:bg-bg-secondary'}`}
                >
                  <div className="font-semibold mb-1 truncate">{chat.title}</div>
                  <div className={`text-xs ${selectedChat?._id === chat._id ? 'text-indigo-200' : 'text-text-muted'}`}>
                    {new Date(chat.createdAt).toLocaleDateString()} at {new Date(chat.createdAt).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                  </div>
                </button>
              ))}
            </div>
          </div>

          {/* Details View */}
          <div className="w-full md:w-2/3 bg-white rounded-xl border border-border-subtle p-6 overflow-y-auto h-[600px]">
            {selectedChat ? (
              <div id="pdf-content" className="bg-white p-2">
                <div className="mb-6 pb-6 border-b border-border-subtle">
                  <div className="flex justify-between items-start mb-4">
                    <div>
                      <h2 className="text-2xl font-bold mb-2">{selectedChat.title}</h2>
                      <p className="text-text-secondary text-sm">
                        Generated on {new Date(selectedChat.createdAt).toLocaleString()}
                      </p>
                    </div>
                    <div className="flex gap-2" data-html2canvas-ignore="true">
                      <button 
                        onClick={handleToggleShare}
                        disabled={isSharing}
                        className={`flex items-center gap-2 px-3 py-2 rounded-lg border transition-colors shadow-sm text-sm font-medium ${selectedChat.isShared ? 'bg-brand/10 border-brand/20 text-brand' : 'bg-bg-secondary hover:bg-border-subtle border-border-strong text-text-secondary hover:text-text-primary'}`}
                        title={selectedChat.isShared ? "Stop sharing" : "Share with students"}
                      >
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                          <circle cx="18" cy="5" r="3"></circle>
                          <circle cx="6" cy="12" r="3"></circle>
                          <circle cx="18" cy="19" r="3"></circle>
                          <line x1="8.59" y1="13.51" x2="15.42" y2="17.49"></line>
                          <line x1="15.41" y1="6.51" x2="8.59" y2="10.49"></line>
                        </svg>
                        {selectedChat.isShared ? 'Shared' : 'Share'}
                      </button>
                      <button 
                        onClick={handleDownloadPdf}
                        data-html2canvas-ignore="true"
                        className="flex items-center justify-center p-2.5 rounded-lg bg-bg-secondary hover:bg-border-subtle border border-border-strong text-text-secondary hover:text-text-primary transition-colors shadow-sm"
                        title="Download as PDF"
                      >
                        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path>
                          <polyline points="7 10 12 15 17 10"></polyline>
                          <line x1="12" y1="15" x2="12" y2="3"></line>
                        </svg>
                      </button>
                    </div>
                  </div>

                  {selectedChat.isShared && (
                    <div data-html2canvas-ignore="true" className="bg-green-50 border border-green-200 rounded-lg p-3 flex items-center justify-between animate-in fade-in slide-in-from-top-2 duration-300">
                      <div className="flex items-center gap-2 text-green-800 text-sm">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"></path><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"></path></svg>
                        <span>Anyone with this link can view this content</span>
                      </div>
                      <button 
                        onClick={copyShareLink}
                        className="text-xs font-semibold bg-white border border-green-200 text-green-700 px-3 py-1.5 rounded-md hover:bg-green-100 transition-colors"
                      >
                        {shareCopied ? 'Copied!' : 'Copy Link'}
                      </button>
                    </div>
                  )}
                </div>

                {(chatType === 'notes' || chatType === 'chat') && parsedData ? (
                  <div className="prose prose-indigo max-w-none text-text-primary">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{parsedData as string}</ReactMarkdown>
                  </div>
                ) : chatType === 'qa' && Array.isArray(parsedData) && parsedData.length > 0 ? (
                  <div className="space-y-4 pb-8">
                    {(parsedData as QA[]).map((qaItem, index) => (
                      <div key={index} className="bg-white border border-border-subtle rounded-xl p-5 shadow-sm pdf-avoid-break">
                        <h3 className="font-semibold text-lg mb-3 flex gap-3 text-text-primary">
                          <span className="text-brand shrink-0">Q.</span> 
                          {qaItem.question}
                        </h3>
                        <div className="pl-8 pt-3 border-t border-border-subtle text-text-secondary">
                           <span className="font-semibold text-brand mr-2">A.</span>
                           {qaItem.answer}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : chatType === 'mcq' && Array.isArray(parsedData) && parsedData.length > 0 ? (
                  <div className="space-y-6 pb-8">
                    {(parsedData as MCQ[]).map((mcq, index) => (
                      <InteractiveMCQ key={index} mcq={mcq} index={index} />
                    ))}
                  </div>
                ) : (
                  <div className="p-4 bg-yellow-50 text-yellow-800 rounded-lg border border-yellow-200">
                    Could not parse the data for this history item. It might be in an older format or corrupted.
                  </div>
                )}
              </div>
            ) : (
              <div className="flex h-full items-center justify-center text-text-muted flex-col gap-4">
                <svg className="w-12 h-12 opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"></path></svg>
                <p>Select a generation from the left to view details</p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
